### ISSUE TITLE
Organizing

### ISSUE THREAD

**Issue by flikka** [OPM/opm-data-legacy#1]
Hi. Good stuff.

There are "several" versions of the SPEX datasets around - eg. the SPE1 first commit f5620e9451510700b20b31b2f40cded19f7125bf has some other friends in the e-room, BENCH_SPE1.DATA and SPE1_opm.data.

Question 1: Can we agree to some metadata (at least), describing the data set in question? 
Quesiton 2: Reference results. Should we put them in a subfolder, next to the actual deck data? I suggest that in any folder, there should only be one input deck (not simple, bench, bla and bla), and in this folder, there can be different reference result folders for different simulators or versions of simulator. 

 But my main concern is that we don't mix different decks in the same folder. Alternatively we have to supply the input deck used, with each set of output.

**Comment by andlaus** [comment]
> Question 1: Can we agree to some metadata (at least), describing the data set in question? 

I'm not sure what you mean. A README file for each data set? I would appreciate that...

> Quesiton 2: Reference results. Should we put them in a subfolder, next to the actual deck data? I suggest that in any folder, there should only be one input deck (not simple, bench, bla and bla), and in this folder, there can be different reference result folders for different simulators or versions of simulator. 

seems like a good idea...

> But my main concern is that we don't mix different decks in the same folder. Alternatively we have to supply the input deck used, with each set of output.

how about subfolders for the more complicated decks? e.g. `norne/full_atw2013/` and `norne/simplified_case1`

**Comment by atgeirr** [comment]
There is a small problem: duplicating all the Norne stuff for each case is extremely wasteful. On my system, I have each .DATA file in a separate case directory, and a softlink to the INCLUDE directory in each case directory. However I do not think softlinks are well supported by git.

I may be wrong about the wastefulness though, git can be quite smart.

**Comment by flikka** [comment]
> I'm not sure what you mean. A README file for each data set? I would appreciate that...

That's indeed what I meant. Sorry for being unclear. Would you mind adding one for the file you put in? 

> how about subfolders for the more complicated decks?

Yes - that's fine by me.

**Comment by flikka** [comment]
Closing this now.
