### ISSUE TITLE
Should we remove ouput_comparator (folder with content)

### ISSUE THREAD

**Issue by flikka** [OPM/opm-data-legacy#130]
The code in the folder https://github.com/OPM/opm-data/tree/master/output_comparator uses ERT's ecl reading to do some comparisons. 

This functionality, I believe, is covered elsewhere now.

Comments? @alfbr?

**Comment by alfbr** [comment]
Yes, all the functionality is now covered elsewhere. I believe it should be removed, but there is no hurry. Those of us who have been working on this are now on vacation. We have a number of PRs to look at when we return before any removal makes sense.

**Comment by akva2** [comment]
this has been done.
