### ISSUE TITLE
Reference results should be pruned

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-data-legacy#313]
The reference results for the integration tests have been moved to the new opm-tests repository and they thus do not serve any useful purpose within opm-data anymore. In conjunction with the fact that they are the reason why cloning opm-data takes so long (cf https://www.youtube.com/watch?time_continue=1&v=r1hL1lvwG9c ), I am of the considerate opinion they should bite the dust and the history of opm-data should be rewritten so that these files no longer need to be downloaded when cloning the repository.

**Comment by alfbr** [comment]
Agreed. I can probably get some work done on it this summer.

**Comment by andlaus** [comment]
is there any progress here? it is *really* annoying to wait 30 minutes just to clone this repo and I think these files should bite the dust before the 2018.10 release.

@akva2: it would probably also be beneficial to only keep old reference results in `opm-tests` for a limited amount of time (6 months?), or we will run into the same github issues with repository size with it sooner or later. I guess discarding old history can be done using a script relatively easily; if you want me to write it for you, ping me.

**Comment by akva2** [comment]
Well if u write it i won't have to..

**Comment by andlaus** [comment]
would somebody please press green for #314? (or raise objections?)
