### ISSUE TITLE
Could anyone upload the UNSMRY file for the Norne case in OPM/opm-data ?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-data-legacy#32]
For analysis and comparison. Thanks.

**Comment by atgeirr** [comment]
To that I add another wish: the script (is it matlab?) used to produce the well curve comparison figures.

**Comment by joakim-hove** [comment]
I am on the UNSMRY; a bit more uncertain about the comparison script.

**Comment by GitPaean** [comment]
I am using MATLAB with some MRST functions, and I think ERT-python can work too.

**Comment by atgeirr** [comment]
> I am on the UNSMRY; a bit more uncertain about the comparison script.

I guess that would be from @totto82.

**Comment by joakim-hove** [comment]
> and I think ERT-python can work too.

It can certainly be done with ERT-Python; I would actually recommend that :-) And be happy to assist in creating some scripts - but I do not think that is what has been used so far.

**Comment by totto82** [comment]
I can add a comparison script for Matlab based on MRST functions. And I suggest that @dr-robertk adds a script based on gnu-plot and ERT.

**Comment by atgeirr** [comment]
I am only asking that you put what you already have here... Or perhaps opm-utilities is better?

**Comment by dr-robertk** [comment]
I have created a PR for opm-data, because the script I created is relatively tailor made for Norne.

**Comment by atgeirr** [comment]
This has been added, closing.
