### ISSUE TITLE
no testcase for the polymer blackoil simulator

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-data-legacy#46]
I get the following when trying to run `flow_polymer` on the only polymer related deck in opm-data:

```
./bin/flow_polymer deck_filename=/home/and/src/opm-data/polymer_test_suite/simple2D/2D_THREEPHASE_POLY_HETER.DATA
[...]
Program threw an exception: [/home/and/src/opm-autodiff/opm/autodiff/NewtonIterationBlackoilCPR.cpp:394] formEllipticSystem() requires 3 phases.
terminate called after throwing an instance of 'std::logic_error'
  what():  [/home/and/src/opm-autodiff/opm/autodiff/NewtonIterationBlackoilCPR.cpp:394] formEllipticSystem() requires 3 phases.
Aborted
```

for me this is quite sub-optimal, because I can't have any confidence that my recent refactorings do not cause regressions. (If you tell me that you'll fix them yourself, I'll open a PR with them anyway, though.) Maybe there's another polymer deck available, but where?

**Comment by atgeirr** [comment]
This points out the (currently) most serious shortcoming of the polymer simulator: there is no working cpr implementation. The workaround is of course to run with use_cpr=false. Use the run.param to run this case.

Making a CPR that works with polymer is perhaps in the works (it should not be too hard), but I do not know. @qilicun perhaps you could comment on this?

I'll close this issue as resolved, but will add an issue to opm-polymer about missing cpr.
