### ISSUE TITLE
reduced_norne cannot be run without manual interference.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-data-legacy#70]
If I try to run reduced_norne/CASE_5_EQUALS_MULTZ_field_barriers/NORNE_C5_3P_EQUIL.DATA it does not find the include files. I have to set a link manually: 

``` sh
educed_norne/CASE_5_EQUALS_MULTZ_field_barriers $ ln -s ../INCLUDE
```

**Comment by GitPaean** [comment]
fixed in OPM/opm-data#71. please take a try.
