### ISSUE TITLE
CPR keyword in SUMMARY section

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-data-legacy#74]
Excerpt from: https://github.com/OPM/opm-parser/pull/587

_The current 'fix' is just to revert the functionality of #581 - but the longer term fix must determine one of two:_
1. _I have found no references to CPR in the SUMMARY section in the documentation, maybe it is a  "bug" in the old SPE9 deck which can be ignored (i.e. just comment out the CPRkeyword from the summary section)._
2. _If it is indeed legitimate with CPR in the SUMMARY section - this suddenly implies that the parser must support section aware keyword schema - now that is a significant change._

So the important question is: "Is `CPR` a valid keyword in the summary section?" Can someone who contributed the original SPE9 dataset shed some light on this?

**Comment by andlaus** [comment]
to me it seems like the CPR keyword is _only_ valid in the summary section (at least according to the documentation), see my comment for OPM/opm-parser#587.

**Comment by joakim-hove** [comment]
I fear there are some version incompatibilities here; I have looked in the 2014.2 version of the manual - and there it is mentioned as valid in the RUNSPEC section. I will try to dig up an older version of the manual.

**Comment by andlaus** [comment]
ok. then it seems like an Eclipse f*ckup: they probably forgot about the SUMMARY keyword and introduced a different one in RUNSPEC. (if it helps, my RM is for version 2011.1)

**Comment by joakim-hove** [comment]
Thank you for input; I found it in the 2014.2 manual as well. So now it is official - we must(?) support keywords with per-section behavior! Ohhh - joy!

**Comment by andlaus** [comment]
reimplementing eclipse bugs is _soo_ much fun ;)

**Comment by joakim-hove** [comment]
> So now it is official - we must(?) support keywords with per-section behavior! Ohhh - joy!

The keyword in question can barely be said to be of major importance, and does probably not warrant the immediate refactoring required to support this. But if someone are aware of other such keywords I would be very glad to hear about them.

**Comment by joakim-hove** [comment]
> ( if it helps, my RM is for version 2011.1)

The RUNSPEC version is not in Eclipse version 2012.2 either - so it came in version 2013/2014.

**Comment by alfbr** [comment]
CPR was introduced in 2014 (as in CPR  preconditioning), so any documentation before that is misleading.

**Comment by andlaus** [comment]
> CPR was introduced in 2014 (as in CPR preconditioning), so any documentation before that is misleading.

except that it is not: in the summary section it was also present before to instruct the simulator to output the well connection pressure. the original SPE9 deck relied on this.

**Comment by alfbr** [comment]
It was, read my comment again (the part in parenthesis), so it seems we have two different CPR keywords on our hands.

**Comment by andlaus** [comment]
> so it seems we have two different CPR keywords on our hands.

right. that is _exactly_ the problem because the syntax of these two versions of CPR suddenly depends on the section.

**Comment by atgeirr** [comment]
Fixed, closing.
