### ISSUE TITLE
Output files missing in opm-data/polymer_test_suite/simple2D/eclipse-simulation/ ?

### ISSUE THREAD

**Issue by flikka** [OPM/opm-data-legacy#77]
Hi - looking at the jenkins tests for the polymer simple2D it seems like some output files (eg. 2D_THREEPHASE_POLY_HETER.UNRST) are missing in the eclipse-simulation? 

Perhaps you have the opportunity to look at this, and add the missing files needed @GitPaean? Thanks.

**Comment by flikka** [comment]
... also missing eclipse-simulation/2D_THREEPHASE_POLY_HETER.EGRID

Could you add this too @qilicun?

**Comment by atgeirr** [comment]
This has been fixed long ago, closing.
