### ISSUE TITLE
About the default.param file for different cases.

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-data-legacy#79]
Some .param files are not indicating the defaulted parameter we are using now, such as the one in Norne directory. I suggest we either update them or delete them. Not updated .param files are misleading and some users asked about the poor performance from using the default.param files.

**Comment by atgeirr** [comment]
I think deleting them is the best in most cases. Those we keep around should demonstrate something different from the default behaviour (i.e. this is how to run with fixed timesteps, or this is how to set tighter tolerances).

**Comment by qilicun** [comment]
I agree.
I just run Norne with the default param file in norne,  the performance is:

/timing/total_time=8001.02
/timing/pressure/total_time=7681.13
/timing/transport/total_time=0
/timing/newton/iterations=3600
/timing/linear/iterations=36811

which make me surprised, it almost 10 times slower than eclipse.

**Comment by atgeirr** [comment]
We have deleted the outdated parameter file, closing.
